preimage:
  over_approx: False
  under_approx: True
  threshold: 0.75
model:
  path: "model_dir/model_2_0.51.pth"
data:
  dataset: cartpole
  num_outputs: 1
  start: 0
  end: 1
specification:
  type: 'bound'  
  robustness_type: "verified-acc"
solver:
  batch_size: 50
bab:
  branching:
    method: "preimg"
    input_split:
      enable: True


